version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    filters:
      branches:
        only:
          - master
        
    steps:
      - checkout
      - run:
          command: ./gradlew build
